sudo: required
services:
  - docker #keep docker service available
before_install: #build image
  - docker build -t bobbyknit007/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true  bobbyknit007/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-891692131162"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
