version: '3'
services:
  web:
  #  build: . # . here this assumes there is a docker file in current folder
    build:
      context: . # get all the files required for image from this directory
      dockerfile: Dockerfile.dev # look for this file in the directory specified by context
    ports:
     - "3000:3000"
    volumes:
     - /app/node_modules # book mark this folder, no mapping should be done against this folder on container
     - .:/app # bind mount this /app folder in container to host file system
  tests: # another service to  run tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # override the defualt command of container
